pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Memulai proses Build...'
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                echo 'Memulai proses Test...'
                sh 'npm test'
            }
        }
    }
}
