pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                // Biasanya di sini 'npm install', tapi kita echo dulu biar HIJAU
                sh 'echo "Build Stage Success"'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                sh 'echo "Test Stage Success"'
            }
        }
    }
}
