pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building React App...'
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing React App...'
                // Menambahkan CI=true agar proses test tidak hang/berjalan terus menerus (standar CI/CD React)
                sh 'CI=true npm test' 
            }
        }
    }
}
